[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"
access-control-allow-origin=""

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "zk1:2181", "zk2:2181", "zk3:2181" ]
timeout=6
root-path="/burrow"

[client-profile.pam]
client-id="pam"
kafka-version="2.0.0"

[cluster.pam]
class-name="kafka"
servers=[ "kfk1:9092", "kfk2:9092", "kfk3:9092" ]
client-profile="pam"
topic-refresh=120
offset-refresh=30
groups-reaper-refresh=0

[consumer.pam]
class-name="kafka"
cluster="pam"
servers=[ "kfk1:9092", "kfk2:9092", "kfk3:9092" ]
client-profile="pam"
group-denylist=""
group-allowlist=""

[consumer.local_zk]
class-name="kafka_zk"
cluster="pam"
servers=[ "zk1:2181", "zk2:2181", "zk3:2181" ]
zookeeper-path="/kafka-cluster"
zookeeper-timeout=30
group-denylist=""
group-allowlist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1

[notifier.default]
class-name="http"
url-open=""
interval=60
timeout=5
keepalive=30
extras={}
template-open="conf/default-http-post.tmpl"
template-close="conf/default-http-delete.tmpl"
method-close="DELETE"
send-close=true
threshold=1